### ISSUE TITLE
Reward Ad

### ISSUE THREAD

**Issue by LinkStatu** [shubham-gupta-16/SimpleWallpaperApp-Android#1]
Can you add Reward Ad? I think the app will be perfect.

**Comment by shubham16g** [comment]
Sure, I will be happy to implement this feature. 
@LinkStatu do you have any suggestions on where to put Reward Ads?

**Comment by LinkStatu** [comment]
@shubham-gupta-16 yeah sure,
Some special and very beautiful wallpapers may be mentioned as "Featured or Premium" wallpapers. A **yellow crown** shape or a **diamond** usually is put at the right or left corner of a wallpaper to represents these wallpapers and to tell the user he must watch a Reward Ad to get them. When he click on that "premium" wallpaper, will be asked; "**You should watch a Video to download this wallpaper**" and the choices would be "yes watch" and "no thanks" or something like that.
My suggestion to make wallpapers premium by adding a new line for every wallpaper in .json file, something like `"IsFeatured": "yes"` to make it easy OR it's up to you to choose the method to implement that. Sorry, but I'm very newbie to implement that yet.
Thanks for your time.

**Comment by shubham16g** [comment]
@LinkStatu Thank you for your idea. I will add this feature very soon😊

**Comment by LinkStatu** [comment]
@shubham-gupta-16
Hi, 
There is a bug in the app. Should I create a new issue or mentioned it here?

**Comment by shubham16g** [comment]
> @shubham-gupta-16 Hi, There is a bug in the app. Should I create a new issue or mentioned it here?

@LinkStatu Yes, you can create a new issue.

**Comment by LinkStatu** [comment]
@shubham-gupta-16 
It looks like you fixed it. The bug was when I download a wallpaper for the first time after installing the app, it's downloaded normally. But when I want to download another wallpaper the app keeps quitting. Now, after you updated the project, this bug is gone.
