### ISSUE TITLE
Collections Screen is Empty 

### ISSUE THREAD

**Issue by aprillins** [shubham-gupta-16/SimpleWallpaperApp-Android#18]
Hi Man!

Thanks for creating such awesome wallpaper app!

I find the Collections screen is empty. Is it a bug, or must I set something in the code?

Thanks!

**Comment by aprillins** [comment]
![Screenshot 2023-07-30 at 15 32 00](https://github.com/shubham-gupta-16/SimpleWallpaperApp-Android/assets/1317947/c07b4179-021a-4b0f-abb4-f3b6468446da)

**Comment by shubham16g** [comment]
I think it's a bug because it is also not working on my device. I have to check.

**Comment by shubham16g** [comment]
Fixed in version `v2.4`
