### ISSUE TITLE
data Collecting in the application

### ISSUE THREAD

**Issue by asdwasem** [shubham-gupta-16/SimpleWallpaperApp-Android#19]
Hello.. Thank you very much for this wonderful application..
I uploaded the application, and after 15 days, I received this message from Google, and I told support that the application does not collect any information, and they pretended that it collects information .. Please, what is the solution?

![WhatsApp Image 2023-07-30 at 14 24 57](https://github.com/shubham-gupta-16/SimpleWallpaperApp-Android/assets/138805096/47a7083d-24ea-4bbc-ab0f-69e39652ace1)
![WhatsApp Image 2023-07-30 at 14 25 18](https://github.com/shubham-gupta-16/SimpleWallpaperApp-Android/assets/138805096/75a710c8-5a0f-4855-99ab-9198fc167cbc)

**Comment by shubham16g** [comment]
You are not collecting and data, but Admob is. So, if your app is using Admob, you should tell that application is collecting data for advertisement purpose. Kindly research more on internet about this or read the Admob policies.
