### ISSUE TITLE
package name changing issue

### ISSUE THREAD

**Issue by sami774** [shubham-gupta-16/SimpleWallpaperApp-Android#23]
Changing the package name crashes my app. I have changed the package name from AndroidManifest.xml and defaultConfig from build.gradle.

Have i done anything wrong?

**Comment by shubham16g** [comment]
To change the package name
- Refactor/Rename the folders (packages). Also, make sure that imports are correct in all files.
- Update the build.gradle
- Update in AndroidManifest.xml
